In [ ]:
# Conectamos con el google drive 
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Instalamos las dependencias de nuestro entorno de trabajo 
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q https://apache.osuosl.org/spark/spark-3.1.3/spark-3.1.3-bin-hadoop2.7.tgz
!tar xf spark-3.1.3-bin-hadoop2.7.tgz
!pip install -q findspark
! pip install koalas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: koalas in /usr/local/lib/python3.7/dist-packages (1.8.2)
Requirement already satisfied: numpy>=1.14 in /usr/local/lib/python3.7/dist-packages (from koalas) (1.21.6)
Requirement already satisfied: pyarrow>=0.10 in /usr/local/lib/python3.7/dist-packages (from koalas) (6.0.1)
Requirement already satisfied: pandas>=0.23.2 in /usr/local/lib/python3.7/dist-packages (from koalas) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.2->koalas) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.2->koalas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23.2->koalas) (1.15.0)

In [ ]:
!ls -a

.	 sample_data			  spark-3.1.3-bin-hadoop2.7.tgz.2
..	 spark-3.1.3-bin-hadoop2.7	  spark-3.1.3-bin-hadoop2.7.tgz.3
.config  spark-3.1.3-bin-hadoop2.7.tgz
drive	 spark-3.1.3-bin-hadoop2.7.tgz.1

In [ ]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.3-bin-hadoop2.7"

In [ ]:
import findspark
findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

In [ ]:
import pandas as pd
import numpy as np
import databricks.koalas as ks

WARNING:root:'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. Koalas will set it for you but it does not work if there is a Spark context already launched.

In [ ]:
#review = spark.read.load("/content/drive/MyDrive/HENRY_TRABAJO_GRUPAL/Repository/Data/review.json", format="json")
#user = spark.read.load("/content/drive/MyDrive/HENRY_TRABAJO_GRUPAL/Repository/Data/user.json", format="json")
#business = spark.read.load("/content/drive/MyDrive/HENRY_TRABAJO_GRUPAL/Repository/Data/business.json", format="json")
checkin = spark.read.load("/content/drive/MyDrive/HENRY_TRABAJO_GRUPAL/Repository/Data/checkin.json", format="json")
#tip= spark.read.load('/content/drive/MyDrive/HENRY_TRABAJO_GRUPAL/Repository/Data/tip.json', format="json")

In [ ]:
#k_review = review.to_koalas() # David
#k_user = user.to_koalas() # Maico
#k_business = business.to_koalas() # Julieta
k_checkin = checkin.to_koalas() # Thiago
#k_tip = tip.to_koalas() # Lila

In [ ]:
k_checkin.columns

Index(['business_id', 'date'], dtype='object')

In [ ]:
def get_len(value):
  ls=value.split(', ')
  return len(ls)

In [ ]:
k_checkin['total'] = k_checkin.date.apply(lambda x: get_len(x))

/content/spark-3.1.3-bin-hadoop2.7/python/pyspark/sql/pandas/functions.py:392: UserWarning: In Python 3.6+ and Spark 3.0+, it is preferred to specify type hints for pandas UDF instead of specifying pandas UDF type which will be deprecated in the future releases. See SPARK-28264 for more details.
  "in the future releases. See SPARK-28264 for more details.", UserWarning)

In [ ]:
k_checkin.head()

              business_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              date  total
0  ---kPU91CF4Lq2-WlRu9Lw                                                                                                                                                                                                                                                                                                                             2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020-07-24 22:42:27, 2020-10-24 21:36:13, 2020-12-09 21:23:33, 2021-01-20 17:34:57, 2021-04-30 21:02:03, 2021-05-25 21:16:54, 2021-08-06 21:08:08, 2021-10-02 15:15:42, 2021-11-11 16:23:50     11
1  --0iUa4sNDFiZFrAdIWhZQ                                                                                                                                                                                                                                                                                                                                                  2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011-07-18 22:30:31, 2012-09-07 20:28:50, 2013-03-27 15:57:36, 2013-08-13 00:31:34, 2013-08-13 00:31:48, 2013-09-23 17:39:38, 2013-11-18 06:34:08, 2014-04-12 23:04:47     10
2  --30_8IhuyMHbSOcNWd6DQ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2013-06-14 23:29:17, 2014-08-13 23:20:22      2
3  --7PUidqRWpRSpXebiyxTg                                                                                                                                                                                                                                                                                                                                                  2011-02-15 17:12:00, 2011-07-28 02:46:10, 2012-03-11 10:30:02, 2012-04-24 07:07:59, 2012-04-24 07:43:31, 2013-05-25 16:41:10, 2014-05-02 15:49:55, 2014-09-18 02:28:23, 2014-11-10 15:16:43, 2015-09-27 13:18:32     10
4  --7jw19RH9JKXgFohspgQw  2014-04-21 20:42:11, 2014-04-28 21:04:46, 2014-09-30 14:41:47, 2014-10-23 18:22:28, 2015-04-27 19:55:00, 2015-09-21 12:52:09, 2015-10-01 12:46:16, 2015-10-22 13:35:04, 2016-01-14 12:27:43, 2016-02-01 15:15:07, 2016-02-11 12:22:47, 2016-03-31 23:15:46, 2016-04-11 13:11:34, 2016-05-25 12:44:11, 2016-06-27 15:46:11, 2016-06-30 15:14:28, 2016-07-28 14:15:59, 2016-09-22 20:05:06, 2016-11-16 19:00:11, 2016-12-27 14:36:14, 2017-01-24 20:18:16, 2017-02-21 16:01:49, 2017-03-21 14:08:44, 2017-05-21 16:07:21, 2017-08-07 14:17:39, 2021-06-21 19:59:50     26

In [ ]:
k_checkin.total.min()

1

In [ ]:
k_checkin.total.max()

52144

In [ ]:
k_checkin.info()

<class 'databricks.koalas.frame.DataFrame'>
Int64Index: 131930 entries, 0 to 131929
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   business_id  131930 non-null  object
 1   date         131930 non-null  object
 2   total        131930 non-null  int64
dtypes: int64(1), object(2)

In [ ]:
len(k_checkin.business_id.unique())

131930

In [ ]:
k_checkin.describe()

               total
count  131930.000000
mean      101.242136
std       417.132327
min         1.000000
25%         6.000000
50%        20.000000
75%        72.000000
max     52144.000000

In [ ]:
from datetime import datetime

In [ ]:
dates_ls = k_checkin.date.to_list()

In [ ]:
dates_ls[0].split(', ')

['2020-03-13 21:10:56',
 '2020-06-02 22:18:06',
 '2020-07-24 22:42:27',
 '2020-10-24 21:36:13',
 '2020-12-09 21:23:33',
 '2021-01-20 17:34:57',
 '2021-04-30 21:02:03',
 '2021-05-25 21:16:54',
 '2021-08-06 21:08:08',
 '2021-10-02 15:15:42',
 '2021-11-11 16:23:50']

In [ ]:
type(k_checkin.date)

databricks.koalas.series.Series

In [ ]:
def get_avg_checkins(dates_list:list):
  hours_sum = 0
  ls = dates_list.split(', ')
  list_len = len(ls)
  for date in ls:
      date_ok = datetime.strptime(date, '%Y-%m-%d %H:%M:%S')
      hours_sum += date_ok.hour
  avg_checkins = hours_sum/list_len
  return round(avg_checkins)

In [ ]:
k_checkin['avg_hour'] = k_checkin.date.apply(get_avg_checkins)

/content/spark-3.1.3-bin-hadoop2.7/python/pyspark/sql/pandas/functions.py:392: UserWarning: In Python 3.6+ and Spark 3.0+, it is preferred to specify type hints for pandas UDF instead of specifying pandas UDF type which will be deprecated in the future releases. See SPARK-28264 for more details.
  "in the future releases. See SPARK-28264 for more details.", UserWarning)

In [ ]:
k_checkin.head()

              business_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              date  total  avg_checkin_hour
0  ---kPU91CF4Lq2-WlRu9Lw                                                                                                                                                                                                                                                                                                                             2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020-07-24 22:42:27, 2020-10-24 21:36:13, 2020-12-09 21:23:33, 2021-01-20 17:34:57, 2021-04-30 21:02:03, 2021-05-25 21:16:54, 2021-08-06 21:08:08, 2021-10-02 15:15:42, 2021-11-11 16:23:50     11                20
1  --0iUa4sNDFiZFrAdIWhZQ                                                                                                                                                                                                                                                                                                                                                  2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011-07-18 22:30:31, 2012-09-07 20:28:50, 2013-03-27 15:57:36, 2013-08-13 00:31:34, 2013-08-13 00:31:48, 2013-09-23 17:39:38, 2013-11-18 06:34:08, 2014-04-12 23:04:47     10                15
2  --30_8IhuyMHbSOcNWd6DQ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2013-06-14 23:29:17, 2014-08-13 23:20:22      2                23
3  --7PUidqRWpRSpXebiyxTg                                                                                                                                                                                                                                                                                                                                                  2011-02-15 17:12:00, 2011-07-28 02:46:10, 2012-03-11 10:30:02, 2012-04-24 07:07:59, 2012-04-24 07:43:31, 2013-05-25 16:41:10, 2014-05-02 15:49:55, 2014-09-18 02:28:23, 2014-11-10 15:16:43, 2015-09-27 13:18:32     10                10
4  --7jw19RH9JKXgFohspgQw  2014-04-21 20:42:11, 2014-04-28 21:04:46, 2014-09-30 14:41:47, 2014-10-23 18:22:28, 2015-04-27 19:55:00, 2015-09-21 12:52:09, 2015-10-01 12:46:16, 2015-10-22 13:35:04, 2016-01-14 12:27:43, 2016-02-01 15:15:07, 2016-02-11 12:22:47, 2016-03-31 23:15:46, 2016-04-11 13:11:34, 2016-05-25 12:44:11, 2016-06-27 15:46:11, 2016-06-30 15:14:28, 2016-07-28 14:15:59, 2016-09-22 20:05:06, 2016-11-16 19:00:11, 2016-12-27 14:36:14, 2017-01-24 20:18:16, 2017-02-21 16:01:49, 2017-03-21 14:08:44, 2017-05-21 16:07:21, 2017-08-07 14:17:39, 2021-06-21 19:59:50     26                16

Checkins per year

In [ ]:
def get_earliest_year(dates_list:list):
  ls = dates_list.split(', ')
  earliest_year = 0
  for date in ls:
      date_ok = datetime.strptime(date, '%Y-%m-%d %H:%M:%S')
      if earliest_year < date_ok.year:
        earliest_year = date_ok.year
  return earliest_year

In [ ]:
k_checkin['earliest_year'] = k_checkin.date.apply(get_earliest_year)

/content/spark-3.1.3-bin-hadoop2.7/python/pyspark/sql/pandas/functions.py:392: UserWarning: In Python 3.6+ and Spark 3.0+, it is preferred to specify type hints for pandas UDF instead of specifying pandas UDF type which will be deprecated in the future releases. See SPARK-28264 for more details.
  "in the future releases. See SPARK-28264 for more details.", UserWarning)

In [ ]:
k_checkin.earliest_year.min()

2010

In [ ]:
def get_yearly_count(dates_list, year):
  ls = dates_list.split(', ')
  yearly_checkins = []
  for date in ls:
      date_ok = datetime.strptime(date, '%Y-%m-%d %H:%M:%S')
      if date_ok.year == year:
        yearly_checkins.append(date_ok)
  return len(yearly_checkins)

In [ ]:
k_checkin['2010'] = k_checkin.date.apply(get_yearly_count, args=(2010,))

In [ ]:
k_checkin.head()

              business_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              date  total  avg_checkin_hour  earliest_year  2010
0  ---kPU91CF4Lq2-WlRu9Lw                                                                                                                                                                                                                                                                                                                             2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020-07-24 22:42:27, 2020-10-24 21:36:13, 2020-12-09 21:23:33, 2021-01-20 17:34:57, 2021-04-30 21:02:03, 2021-05-25 21:16:54, 2021-08-06 21:08:08, 2021-10-02 15:15:42, 2021-11-11 16:23:50     11                20           2021     0
1  --0iUa4sNDFiZFrAdIWhZQ                                                                                                                                                                                                                                                                                                                                                  2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011-07-18 22:30:31, 2012-09-07 20:28:50, 2013-03-27 15:57:36, 2013-08-13 00:31:34, 2013-08-13 00:31:48, 2013-09-23 17:39:38, 2013-11-18 06:34:08, 2014-04-12 23:04:47     10                15           2014     1
2  --30_8IhuyMHbSOcNWd6DQ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2013-06-14 23:29:17, 2014-08-13 23:20:22      2                23           2014     0
3  --7PUidqRWpRSpXebiyxTg                                                                                                                                                                                                                                                                                                                                                  2011-02-15 17:12:00, 2011-07-28 02:46:10, 2012-03-11 10:30:02, 2012-04-24 07:07:59, 2012-04-24 07:43:31, 2013-05-25 16:41:10, 2014-05-02 15:49:55, 2014-09-18 02:28:23, 2014-11-10 15:16:43, 2015-09-27 13:18:32     10                10           2015     0
4  --7jw19RH9JKXgFohspgQw  2014-04-21 20:42:11, 2014-04-28 21:04:46, 2014-09-30 14:41:47, 2014-10-23 18:22:28, 2015-04-27 19:55:00, 2015-09-21 12:52:09, 2015-10-01 12:46:16, 2015-10-22 13:35:04, 2016-01-14 12:27:43, 2016-02-01 15:15:07, 2016-02-11 12:22:47, 2016-03-31 23:15:46, 2016-04-11 13:11:34, 2016-05-25 12:44:11, 2016-06-27 15:46:11, 2016-06-30 15:14:28, 2016-07-28 14:15:59, 2016-09-22 20:05:06, 2016-11-16 19:00:11, 2016-12-27 14:36:14, 2017-01-24 20:18:16, 2017-02-21 16:01:49, 2017-03-21 14:08:44, 2017-05-21 16:07:21, 2017-08-07 14:17:39, 2021-06-21 19:59:50     26                16           2021     0

In [ ]:
for x in range(2011, 2022):
  k_checkin[str(x)] = k_checkin.date.apply(get_yearly_count, args=(x,))

/content/spark-3.1.3-bin-hadoop2.7/python/pyspark/sql/pandas/functions.py:392: UserWarning: In Python 3.6+ and Spark 3.0+, it is preferred to specify type hints for pandas UDF instead of specifying pandas UDF type which will be deprecated in the future releases. See SPARK-28264 for more details.
  "in the future releases. See SPARK-28264 for more details.", UserWarning)

In [ ]:
k_checkin.head()

              business_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              date  total  avg_checkin_hour  earliest_year  2010  2011  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0  ---kPU91CF4Lq2-WlRu9Lw                                                                                                                                                                                                                                                                                                                             2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020-07-24 22:42:27, 2020-10-24 21:36:13, 2020-12-09 21:23:33, 2021-01-20 17:34:57, 2021-04-30 21:02:03, 2021-05-25 21:16:54, 2021-08-06 21:08:08, 2021-10-02 15:15:42, 2021-11-11 16:23:50     11                20           2021     0     0     0     0     0     0     0     0     0     0     5     6
1  --0iUa4sNDFiZFrAdIWhZQ                                                                                                                                                                                                                                                                                                                                                  2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011-07-18 22:30:31, 2012-09-07 20:28:50, 2013-03-27 15:57:36, 2013-08-13 00:31:34, 2013-08-13 00:31:48, 2013-09-23 17:39:38, 2013-11-18 06:34:08, 2014-04-12 23:04:47     10                15           2014     1     2     1     5     1     0     0     0     0     0     0     0
2  --30_8IhuyMHbSOcNWd6DQ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2013-06-14 23:29:17, 2014-08-13 23:20:22      2                23           2014     0     0     0     1     1     0     0     0     0     0     0     0
3  --7PUidqRWpRSpXebiyxTg                                                                                                                                                                                                                                                                                                                                                  2011-02-15 17:12:00, 2011-07-28 02:46:10, 2012-03-11 10:30:02, 2012-04-24 07:07:59, 2012-04-24 07:43:31, 2013-05-25 16:41:10, 2014-05-02 15:49:55, 2014-09-18 02:28:23, 2014-11-10 15:16:43, 2015-09-27 13:18:32     10                10           2015     0     2     3     1     3     1     0     0     0     0     0     0
4  --7jw19RH9JKXgFohspgQw  2014-04-21 20:42:11, 2014-04-28 21:04:46, 2014-09-30 14:41:47, 2014-10-23 18:22:28, 2015-04-27 19:55:00, 2015-09-21 12:52:09, 2015-10-01 12:46:16, 2015-10-22 13:35:04, 2016-01-14 12:27:43, 2016-02-01 15:15:07, 2016-02-11 12:22:47, 2016-03-31 23:15:46, 2016-04-11 13:11:34, 2016-05-25 12:44:11, 2016-06-27 15:46:11, 2016-06-30 15:14:28, 2016-07-28 14:15:59, 2016-09-22 20:05:06, 2016-11-16 19:00:11, 2016-12-27 14:36:14, 2017-01-24 20:18:16, 2017-02-21 16:01:49, 2017-03-21 14:08:44, 2017-05-21 16:07:21, 2017-08-07 14:17:39, 2021-06-21 19:59:50     26                16           2021     0     0     0     0     4     4    12     5     0     0     0     1